services:
  zero2prod:
    image: zero2prod
    build: .
    container_name: zero2prod_container
    environment:
      - APP_ENVIRONMENT=production
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-zero2prod}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zero2prod}
      POSTGRES_DB: ${POSTGRES_DB:-zero2prod}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_MAX_CONNECTIONS: '1000'
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
