#file: noinspection ComposeUnknownValues,ComposeUnknownKeys
#
# https://youtrack.jetbrains.com/issue/IJPL-164262
#

name: zero2prod
region: fra
services:
  - name: zero2prod
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: pawaclawczyk/zero2prod
    health_check:
      http_path: /health_check
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: APP_DATABASE__USERNAME
        scope: RUN_TIME
        value: ${newsletter.USERNAME}
      - key: APP_DATABASE__PASSWORD
        scope: RUN_TIME
        value: ${newsletter.PASSWORD}
      - key: APP_DATABASE__HOST
        scope: RUN_TIME
        value: ${newsletter.HOSTNAME}
      - key: APP_DATABASE__PORT
        scope: RUN_TIME
        value: ${newsletter.PORT}
      - key: APP_DATABASE__DATABASE_NAME
        scope: RUN_TIME
        value: ${newsletter.DATABASE}
databases:
  - name: newsletter
    engine: PG
    version: "17"
    production: false
ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: zero2prod
jobs:
  - name: migrate
    github:
      repo: pawaclawczyk/zero2prod
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    envs:
      - key: DATABASE_URL
        value: "${newsletter.DATABASE_URL}"
        scope: RUN_TIME
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    kind: POST_DEPLOY
